<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('requisition_forms', function (Blueprint $table) {
            $table->id('request_id');
            $table->string('access_code', 10)->unique();
            $table->unsignedTinyInteger('status_id')->index();

            // Contact information
            $table->enum('user_type', ['Internal', 'External'])->default('External');
            $table->string('first_name', 50);
            $table->string('last_name', 50);
            $table->string('email', 100);
            $table->string('school_id', 20)->nullable();
            $table->string('organization_name', 100)->nullable();
            $table->string('contact_number', 15)->nullable();

            // Event details
            $table->string('event_title', 100);
            $table->text('event_details')->nullable(); // this is now required. this is where the user explains their purpose of use. department heads, schedule coordinators, and deans can now review and endorse the request in the system instead of users having to visit each office to get signatures. this also allows for better tracking and accountability.
            $table->unsignedTinyInteger('purpose_id')->index();
            $table->integer('num_participants');
            $table->text('additional_requests')->nullable();
            $table->unsignedInteger('num_tables')->default(0);
            $table->unsignedInteger('num_chairs')->default(0);
            $table->unsignedInteger('num_microphones')->default(0);

            // User uploads
            $table->string('event_documents_url')->nullable();
            $table->string('event_documents_public_id')->nullable();
            $table->string('proof_of_payment_url')->nullable();
            $table->string('proof_of_payment_public_id')->nullable();
            $table->string('upload_token', 100)->nullable();

            // booking schedule 
            $table->date('start_date')->index();
            $table->date('end_date')->index();
            $table->time('start_time');
            $table->time('end_time');
            $table->boolean('all_day')->default(false);

            // late returns 
            $table->decimal('late_penalty_fee', 10, 2)->default(0);
            $table->boolean('is_late')->default(false);
            $table->dateTime('returned_at')->nullable(); // deprecated; moved to separate equipment transactions table

            // fees set by admins
            $table->decimal('tentative_fee', 10, 2)->nullable(); // base fee of facilities & equipment calculated by the system 
            $table->decimal('approved_fee', 10, 2)->nullable(); // base fee + additionals approved by admin after review

            // finalize form
            $table->boolean('is_finalized')->default(false);
            $table->dateTime('finalized_at')->nullable();
            $table->unsignedBigInteger('finalized_by')->nullable();

            // official receipt - generated by system once proof_of_payment = not null and is_finalized = true; unique to prevent duplicates and ensure one receipt per finalized form
            $table->string('official_receipt_num', 20)->nullable()->unique();

            // close form
            $table->boolean('is_closed')->default(false);
            $table->dateTime('closed_at')->nullable();
            $table->unsignedBigInteger('closed_by')->nullable();
            $table->string('closure_reason', 255)->nullable();

            $table->timestamps();

            // Foreign Keys
            $table->foreign('purpose_id')->references('purpose_id')->on('requisition_purposes')->onDelete('restrict');
            $table->foreign('status_id')->references('status_id')->on('form_statuses')->onDelete('restrict');
            $table->foreign('finalized_by')->references('admin_id')->on('admins')->onDelete('set null');
            $table->foreign('closed_by')->references('admin_id')->on('admins')->onDelete('set null');

            // 1. Index for sorting by creation date (used in pagination)
            $table->index('created_at');

            // 2. COMPOSITE INDEX - MOST IMPORTANT FOR YOUR PENDING REQUESTS
            // Combines status and date for your specific query pattern
            $table->index(['status_id', 'created_at']);

            // 3. Index for organization_name if you search by it
            $table->index('organization_name');

            // 4. Index for email if you search by requester
            $table->index('email');

            // 5. Composite index for date ranges (start_date + end_date together)
            $table->index(['start_date', 'end_date']);
        });
    }
};

