<?php
// app/Http/Controllers/ScannerController.php

namespace App\Http\Controllers;

use App\Models\EquipmentItem;
use App\Models\EquipmentTransaction;
use App\Services\ScannerService;
use App\Services\TransactionService;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;

class ScannerController extends Controller
{
    public function __construct(
        protected ScannerService $scannerService,
        protected TransactionService $transactionService
    ) {
    }
    /**
     * Handle barcode scanning and return equipment details
     */
    public function scan(Request $request): JsonResponse
    {
        $request->validate(['barcode' => 'required|string']);

        try {
            $barcode = $this->scannerService->cleanBarcode($request->barcode);

            Log::info('Scanner: Attempting to scan barcode', ['barcode' => $barcode]);

            $item = $this->scannerService->findItemByBarcode($barcode);

            if (!$item) {
                Log::warning('Scanner: Equipment item not found', ['barcode' => $barcode]);
                return response()->json(
                    $this->scannerService->formatError(
                        'Equipment item not found. Please ensure:
                    1. The barcode was generated by the system
                    2. The equipment item exists in the database
                    3. The barcode is properly scanned',
                        404
                    ),
                    404
                );
            }

            Log::info('Scanner: Equipment item found', [
                'item_id' => $item->item_id,
                'barcode' => $item->barcode_number
            ]);

            $currentBookings = $this->scannerService->getCurrentBookings($item->equipment_id);
            $stockData = $this->scannerService->calculateStockAvailability($item->equipment_id, $currentBookings);
            $activeTransaction = $this->scannerService->getActiveTransaction($item->item_id);

            // Get reserved requisitions for this equipment type
            $reservedRequisitions = $this->getReservedRequisitionsForEquipment($item->equipment_id);

            $responseData = $this->scannerService->formatItemResponse(
                $item,
                $stockData,
                $activeTransaction,
                $currentBookings,
                $barcode
            );

            // Add reserved requisitions to the response
            $responseData['reserved_requisitions'] = $reservedRequisitions;

            Log::info('Scanner: Successfully processed scan', [
                'item_id' => $item->item_id,
                'available_stock' => $stockData['available_stock'],
                'has_active_transaction' => !is_null($activeTransaction),
                'reserved_requisitions_count' => count($reservedRequisitions)
            ]);

            return response()->json($responseData);

        } catch (\Exception $e) {
            Log::error('Scanner: Error scanning barcode', [
                'barcode' => $request->barcode,
                'error' => $e->getMessage()
            ]);

            return response()->json(
                $this->scannerService->formatError('Failed to scan barcode: ' . $e->getMessage(), 500),
                500
            );
        }
    }

    /**
     * Get reserved requisitions that include the specified equipment
     */
    private function getReservedRequisitionsForEquipment($equipmentId): array
    {
        $reservedStatus = \App\Models\FormStatus::where('status_name', 'Reserved')->first();

        if (!$reservedStatus) {
            return [];
        }

        $requisitions = \App\Models\RequisitionForm::where('status_id', $reservedStatus->status_id)
            ->whereHas('requestedEquipment', function ($query) use ($equipmentId) {
                $query->where('equipment_id', $equipmentId);
            })
            ->with([
                'requestedEquipment' => function ($query) use ($equipmentId) {
                    $query->where('equipment_id', $equipmentId);
                }
            ])
            ->get();

        return $requisitions->map(function ($req) use ($equipmentId) {
            $requestedEq = $req->requestedEquipment->first();
            return [
                'request_id' => $req->request_id,
                'first_name' => $req->first_name,
                'last_name' => $req->last_name,
                'organization_name' => $req->organization_name,
                'start_date' => $req->start_date,
                'end_date' => $req->end_date,
                'quantity' => $requestedEq ? $requestedEq->quantity : 0
            ];
        })->toArray();
    }

    /**
     * Handle borrow request - Create transaction record
     */
    public function borrow(Request $request): JsonResponse
    {
        $request->validate([
            'barcode' => 'required|string',
            'request_id' => 'nullable|exists:requisition_forms,request_id',
            'facility_id' => 'nullable|exists:facilities,facility_id',
            'destination_name' => 'nullable|string|max:255',
            'notes' => 'nullable|string'
        ]);

        try {
            $validation = $this->scannerService->validateBorrowRequest(
                $request->barcode,
                $request->request_id ?? null
            );

            if (isset($validation['error'])) {
                $additionalData = isset($validation['transaction'])
                    ? ['transaction' => $validation['transaction']]
                    : null;

                return response()->json(
                    $this->scannerService->formatError($validation['error'], 400, $additionalData),
                    400
                );
            }

            // Create the transaction first
            $transactionData = [
                'item_id' => $validation['item']->item_id,
                'released_by' => auth()->id(),
            ];

            if ($request->request_id) {
                $transactionData['request_id'] = $request->request_id;
                $transactionData['requested_equipment_id'] = $validation['requested_equipment']->requested_equipment_id;
            }

            $transaction = EquipmentTransaction::create($transactionData);

            // Now release it
            $transaction = $this->transactionService->releaseItem(
                $transaction,
                $request->facility_id,
                $request->destination_name,
                $request->notes
            );

            Log::info('Scanner: Item borrowed and transaction created', [
                'item_id' => $validation['item']->item_id,
                'barcode' => $request->barcode,
                'transaction_id' => $transaction->id
            ]);

            return response()->json(
                $this->scannerService->formatBorrowResponse($transaction, $validation['item'])
            );

        } catch (\Exception $e) {
            Log::error('Scanner: Error processing borrow request', [
                'barcode' => $request->barcode,
                'error' => $e->getMessage()
            ]);

            return response()->json(
                $this->scannerService->formatError('Failed to process borrow request: ' . $e->getMessage(), 500),
                500
            );
        }
    }

    /**
     * Handle return request - Find active transaction
     */
    public function return(Request $request): JsonResponse
    {
        $request->validate(['barcode' => 'required|string']);

        try {
            $validation = $this->scannerService->validateReturnRequest($request->barcode);

            if (isset($validation['error'])) {
                return response()->json(
                    $this->scannerService->formatError($validation['error'], 400),
                    400
                );
            }

            return response()->json(
                $this->scannerService->formatReturnModalResponse($validation['item'], $validation['transaction'])
            );

        } catch (\Exception $e) {
            Log::error('Scanner: Error processing return request', [
                'barcode' => $request->barcode,
                'error' => $e->getMessage()
            ]);

            return response()->json(
                $this->scannerService->formatError('Failed to process return request: ' . $e->getMessage(), 500),
                500
            );
        }
    }

    /**
     * Handle item update from scanner modal and complete return
     */
    public function updateItem(Request $request, $itemId): JsonResponse
    {
        $request->validate([
            'item_name' => 'required|string|max:50',
            'condition_id' => 'required|exists:conditions,condition_id',
            'item_notes' => 'nullable|string',
            'transaction_id' => 'required|exists:equipment_transactions,id'
        ]);

        try {
            $item = EquipmentItem::findOrFail($itemId);
            $transaction = EquipmentTransaction::findOrFail($request->transaction_id);

            if ($transaction->item_id !== $item->item_id) {
                return response()->json(
                    $this->scannerService->formatError('Transaction does not match this item', 400),
                    400
                );
            }

            DB::transaction(function () use ($item, $request, $transaction) {
                $item->update([
                    'item_name' => $request->item_name,
                    'condition_id' => $request->condition_id,
                    'item_notes' => $request->item_notes,
                    'updated_by' => auth()->id()
                ]);

                $this->transactionService->returnItem(
                    $transaction,
                    $request->condition_id,
                    $request->item_notes
                );
            });

            Log::info('Scanner: Item returned and transaction completed', [
                'item_id' => $item->item_id,
                'transaction_id' => $transaction->id
            ]);

            return response()->json([
                'status' => 'success',
                'message' => 'Item returned successfully',
                'item' => [
                    'item_id' => $item->item_id,
                    'item_name' => $item->item_name,
                    'condition_id' => $item->condition_id,
                    'status_id' => $item->status_id,
                    'item_notes' => $item->item_notes
                ]
            ]);

        } catch (\Exception $e) {
            Log::error('Scanner: Error updating item', [
                'item_id' => $itemId,
                'error' => $e->getMessage()
            ]);

            return response()->json(
                $this->scannerService->formatError('Failed to update item: ' . $e->getMessage(), 500),
                500
            );
        }
    }

    /**
     * Get active transaction for an item
     */
    public function getActiveTransaction($barcode): JsonResponse
    {
        try {
            $item = EquipmentItem::where('barcode_number', $barcode)->first();

            if (!$item) {
                return response()->json(
                    $this->scannerService->formatError('Item not found', 404),
                    404
                );
            }

            $transaction = $this->scannerService->getActiveTransaction($item->item_id);

            return response()->json([
                'status' => 'success',
                'transaction' => $transaction
            ]);

        } catch (\Exception $e) {
            return response()->json(
                $this->scannerService->formatError($e->getMessage(), 500),
                500
            );
        }
    }
}